DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS code;

CREATE TABLE user(
	id TEXT PRIMARY KEY NOT NULL,
	email TEXT UNIQUE NOT NULL,
	username TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	code_used TEXT,
	verified INT,
	verif_token TEXT
);

CREATE TABLE code(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	codeVal TEXT UNIQUE NOT NULL
);
